/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/strava/event": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Strava webhook subscription handshake. Strava calls this with hub.mode/hub.verify_token/hub.challenge query params; we echo the challenge if the verify token matches. */
    get: operations["getApiStravaEvent"];
    put?: never;
    /** @description Strava webhook delivery. Authenticated by matching subscription_id against STRAVA_SUBSCRIPTION_ID; processing is fire-and-forget. */
    post: operations["postApiStravaEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Liveness probe */
    get: operations["getApiHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/privacy-policy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Public privacy policy as Markdown. */
    get: operations["getApiPrivacyPolicy"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/terms-of-service": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Public terms of service as Markdown. */
    get: operations["getApiTermsOfService"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/intervals/event": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Intervals.icu webhook delivery. Authenticated by matching the shared secret against INTERVALS_WEBHOOK_SECRET; processing is fire-and-forget. */
    post: operations["postApiIntervalsEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description List activities for the authenticated user */
    post: operations["postApiActivity"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get full activity details (all stored columns) for a single activity */
    get: operations["getApiActivityById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity/{id}/segments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get interval segments for an activity */
    get: operations["getApiActivityByIdSegments"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity/update": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Update activity metadata (trainingType, notes, feeling) */
    post: operations["postApiActivityUpdate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity/gear/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get aggregated usage statistics for each shoe/gear item */
    get: operations["getApiActivityGearStats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity/{id}/laps": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get Strava laps for an activity */
    get: operations["getApiActivityByIdLaps"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity/{id}/splits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get Strava metric splits for an activity */
    get: operations["getApiActivityByIdSplits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity/{id}/heartrate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get heartrate stream for an activity */
    get: operations["getApiActivityByIdHeartrate"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents/pending": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get activities pending analysis (re-queues skipped_inactive and error rows). */
    get: operations["getApiAgentsPending"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents/start-analysis": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Start the LangGraph analysis pipeline for an activity */
    post: operations["postApiAgentsStartAnalysis"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents/resume-analysis": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Resume the LangGraph analysis pipeline after user input */
    post: operations["postApiAgentsResumeAnalysis"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents/proposed-pace": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Get proposed paces for an interval structure */
    post: operations["postApiAgentsProposedPace"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents/parse-intervals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Parse a free-text workout description (e.g. '6x800m @ 3:45 with 90s rest') into ExpandedIntervalSet[] with proposed paces filled. */
    post: operations["postApiAgentsParseIntervals"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/strava/auth/url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Build the Strava OAuth authorization URL the client should redirect the user to. Always returns the same URL pattern for the configured client. */
    get: operations["getApiStravaAuthUrl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/strava/auth/exchange": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Exchange a Strava OAuth `code` for tokens, store them in Clerk private metadata, and link the Strava athlete to the authenticated Clerk user. */
    post: operations["postApiStravaAuthExchange"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/strava/sync/activities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List the authenticated user's Strava activities (forwarded from Strava v3 /athlete/activities) and filter out activities already imported into our DB. Pagination is forwarded via `page` and `per_page`. */
    get: operations["getApiStravaSyncActivities"];
    put?: never;
    /** @description Import a list of Strava activity IDs into our DB. Each activity is fetched in detail, inserted (skipping conflicts), and queued for LangGraph analysis. */
    post: operations["postApiStravaSyncActivities"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/strava/webhook/subscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Create the Strava push subscription pointing back to /api/strava/event. Idempotent — Strava rejects duplicates with 400. */
    get: operations["getApiStravaWebhookSubscribe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/strava/webhook/subscription": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List existing Strava push subscriptions for our application client. Useful for verifying the current subscription ID before deleting/recreating. */
    get: operations["getApiStravaWebhookSubscription"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/strava/webhook/subscription/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Delete a Strava push subscription by ID. */
    delete: operations["deleteApiStravaWebhookSubscriptionById"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/interval-structures/filter": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get distinct interval structures for the authenticated user */
    get: operations["getApiIntervalStructuresFilter"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get dashboard summary, graph data, and averages */
    get: operations["getApiDashboard"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/dashboard/training-summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Current intervals.icu training-summary snapshot. Always returns an object discriminated by `status`: `ok` (data populated with latest wellness record — fitness model, sleep, recovery, body), `not_linked` (intervals.icu not connected), or `no_recent_data` (linked, but no wellness records in the past 7 days). All metrics in `data` are auto/device-sourced (no subjective fields). */
    get: operations["getApiDashboardTrainingSummary"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/dashboard/wellness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Daily intervals.icu wellness series for the requested date range. Discriminated by `status`: `ok` (per-day points + summary stats + metricsAvailable for the picker), `not_linked` (intervals.icu not connected), `no_data` (linked but no records in range). Each point groups fields into `fitness` (CTL/ATL/TSB/load), `sleep`, `recovery` (RHR/HRV/readiness/SpO2/respiration), `subjective` (soreness/fatigue/stress/mood/motivation, 1–4 scale), `health` (injury/sickness flags), `body` (weight/bodyFat/VO2max), and free-text `comments`. Range capped at 366 days; oldest must be ≤ newest. */
    get: operations["getApiDashboardWellness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/dashboard/week/{weekStart}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get detailed stats for a specific week */
    get: operations["getApiDashboardWeekByWeekStart"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List every event for the authenticated user, newest occurrence first. Optional filters: `status` (active/resolved), `eventType`. */
    get: operations["getApiEvents"];
    put?: never;
    /** @description Create a new event and link it to one of the user's activities. `startTime` defaults to the activity's start date when omitted. */
    post: operations["postApiEvents"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Unlink an event from the given activity. When that was the event's only linked activity, the event itself is deleted. */
    delete: operations["deleteApiEventsById"];
    options?: never;
    head?: never;
    /** @description Edit an event (description, body location, type, status). Toggling `status` keeps `resolvedAt` in sync. */
    patch: operations["patchApiEventsById"];
    trace?: never;
  };
  "/api/user": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get the authenticated user's profile and consent settings */
    get: operations["getApiUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Update the authenticated user's settings. processHeartRate is the GDPR Art 9 consent toggle for heart-rate processing. */
    patch: operations["patchApiUser"];
    trace?: never;
  };
  "/api/user/accept-privacy-policy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Record the authenticated user's acceptance of the current privacy policy version. */
    post: operations["postApiUserAcceptPrivacyPolicy"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/accept-terms-of-service": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Record the authenticated user's acceptance of the current terms of service version. */
    post: operations["postApiUserAcceptTermsOfService"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/data": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Permanently delete the authenticated user's account: removes all activities (interval segments cascade), the user row, revokes Strava OAuth, and clears Clerk metadata. */
    delete: operations["deleteApiUserData"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/intervals/auth/exchange": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiIntervalsAuthExchange"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getApiStravaEvent: {
    parameters: {
      query?: {
        "hub.mode"?: string;
        "hub.verify_token"?: string;
        "hub.challenge"?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Handshake accepted; echoes hub.challenge */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            "hub.challenge"?: string;
          };
        };
      };
      /** @description Verification failed (token mismatch or invalid mode) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  postApiStravaEvent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          object_type: "activity" | "athlete";
          object_id: number;
          /** @enum {string} */
          aspect_type: "create" | "update" | "delete";
          updates?: {
            [key: string]: unknown;
          };
          owner_id: number;
          subscription_id: number;
          event_time: number;
        };
      };
    };
    responses: {
      /** @description Event accepted for background processing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            status: "ok" | "unauthorized";
          };
        };
      };
      /** @description subscription_id did not match */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            status: "ok" | "unauthorized";
          };
        };
      };
    };
  };
  getApiHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  getApiPrivacyPolicy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Privacy policy markdown source */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/markdown": string;
        };
      };
    };
  };
  getApiTermsOfService: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Terms of service markdown source */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/markdown": string;
        };
      };
    };
  };
  postApiIntervalsEvent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          secret: string;
          events: (
            | {
                /** @enum {string} */
                type:
                  | "ACTIVITY_UPLOADED"
                  | "ACTIVITY_UPDATED"
                  | "ACTIVITY_ANALYZED"
                  | "ACTIVITY_DELETED";
                athlete_id: string;
                timestamp?: string;
                activity?: {
                  id: string | number;
                } & {
                  [key: string]: unknown;
                };
              }
            | {
                /** @constant */
                type: "APP_SCOPE_CHANGED";
                athlete_id: string;
                timestamp?: string;
              }
            | {
                /** @constant */
                type: "TEST";
                athlete_id: string;
                timestamp?: string;
              }
            | ({
                type: string;
                athlete_id: string;
                timestamp?: string;
              } & {
                [key: string]: unknown;
              })
          )[];
        };
      };
    };
    responses: {
      /** @description Event accepted for background processing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            status: "ok" | "unauthorized";
          };
        };
      };
      /** @description Shared secret did not match */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            status: "ok" | "unauthorized";
          };
        };
      };
    };
  };
  postApiActivity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @default 1 */
          page?: number;
          search?: string;
          distance?: number;
          trainingType?: (
            | "LONG"
            | "EASY"
            | "RECOVERY"
            | "SHORT_INTERVALS"
            | "HILL_SPRINTS"
            | "LONG_INTERVALS"
            | "SPRINTS"
            | "FARTLEK"
            | "PROGRESSIVE_LONG"
            | "RACE"
            | "TEMPO"
            | "OTHER"
          )[];
          intervalStructureId?: number;
          sportTypes?: string[];
          signatures?: string[];
          /** Format: date-time */
          dateFrom?: string;
          /** Format: date-time */
          dateTo?: string;
          eventTypes?: ("INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER")[];
          eventIds?: number[];
        };
      };
    };
    responses: {
      /** @description Paginated activity list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: {
              id: number;
              title: string;
              startDateLocal: string;
              distance: number;
              sportType: string;
              indoor: boolean;
              /** @enum {string|null} */
              trainingType:
                | "LONG"
                | "EASY"
                | "RECOVERY"
                | "SHORT_INTERVALS"
                | "HILL_SPRINTS"
                | "LONG_INTERVALS"
                | "SPRINTS"
                | "FARTLEK"
                | "PROGRESSIVE_LONG"
                | "RACE"
                | "TEMPO"
                | "OTHER"
                | null;
              trainingLoad: number | null;
              icuTrainingLoad: number | null;
              averageHeartRate: number | null;
            }[];
            meta: {
              page: number;
              pageSize: number;
              filterApplied: {
                search?: string;
                /** @enum {string} */
                trainingType?:
                  | "LONG"
                  | "EASY"
                  | "RECOVERY"
                  | "SHORT_INTERVALS"
                  | "HILL_SPRINTS"
                  | "LONG_INTERVALS"
                  | "SPRINTS"
                  | "FARTLEK"
                  | "PROGRESSIVE_LONG"
                  | "RACE"
                  | "TEMPO"
                  | "OTHER";
                distance?: number;
                intervalStructureId?: number;
                sportTypes?: string[];
                signatures?: string[];
                dateFrom?: string;
                dateTo?: string;
                eventTypes?: ("INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER")[];
                eventIds?: number[];
              };
            };
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiActivityById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Activity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            userId: string;
            /** @enum {string|null} */
            trainingType:
              | "LONG"
              | "EASY"
              | "RECOVERY"
              | "SHORT_INTERVALS"
              | "HILL_SPRINTS"
              | "LONG_INTERVALS"
              | "SPRINTS"
              | "FARTLEK"
              | "PROGRESSIVE_LONG"
              | "RACE"
              | "TEMPO"
              | "OTHER"
              | null;
            intervalStructureId: number | null;
            analyzedAt: string | null;
            /** @enum {string|null} */
            analysisStatus:
              | "pending"
              | "ongoing_init"
              | "initial"
              | "ongoing_completed"
              | "completed"
              | "error"
              | "skipped_inactive"
              | null;
            draftAnalysisResult?: null;
            analysisVersion: string | null;
            stravaActivityId: number;
            gearId: string | null;
            hasHeartrate: boolean | null;
            title: string;
            description: string | null;
            sportType: string;
            distance: number;
            movingTime: number;
            totalElevationGain: number | null;
            averageHeartRate: number | null;
            startDateLocal: string;
            feeling: number | null;
            notes: string | null;
            createdAt: string | null;
            indoor: boolean;
            intervalsIcuId?: string | null;
            intervalsAnalyzed?: boolean | null;
            intervalsIcuEnrichedAt?: string | null;
            elapsedTime?: number | null;
            maxHeartRate?: number | null;
            averagePower?: number | null;
            weightedAveragePower?: number | null;
            calories?: number | null;
            deviceName?: string | null;
            trainingLoad?: number | null;
            icuTrainingLoad?: number | null;
            icuIntensity?: number | null;
            relativeIntensity?: number | null;
            decoupling?: number | null;
            polarizationIndex?: number | null;
            icuFtp?: number | null;
            icuCtl?: number | null;
            icuAtl?: number | null;
            events?: {
              id: number;
              /** @enum {string} */
              eventType: "INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER";
              bodyLocation: string | null;
              description: string;
              startTime: string;
              lastOccurrence: string;
              /** @enum {string} */
              status: "active" | "resolved";
              resolvedAt: string | null;
            }[];
          };
        };
      };
      /** @description Invalid activity ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Activity not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiActivityByIdSegments: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Interval segments */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            intervalSegments: {
              id: number;
              activityId: number;
              segmentIndex: number;
              setGroupIndex: number;
              /** @enum {string} */
              type: "INTERVALS" | "REST" | "ACTIVE_REST" | "WARMUP" | "COOL_DOWN" | "JOGGING";
              targetValue: number;
              /** @enum {string} */
              targetType: "time" | "distance" | "custom";
              targetPace: number | null;
              timeSeriesEndTime: number;
              actualDistance: number;
              actualDuration: number;
              avgHeartRate: number | null;
            }[];
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  postApiActivityUpdate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          id: number;
          /** @enum {string|null} */
          trainingType?:
            | "LONG"
            | "EASY"
            | "RECOVERY"
            | "SHORT_INTERVALS"
            | "HILL_SPRINTS"
            | "LONG_INTERVALS"
            | "SPRINTS"
            | "FARTLEK"
            | "PROGRESSIVE_LONG"
            | "RACE"
            | "TEMPO"
            | "OTHER"
            | null;
          notes?: string | null;
          feeling?: number | null;
        };
      };
    };
    responses: {
      /** @description Updated activity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            userId: string;
            /** @enum {string|null} */
            trainingType:
              | "LONG"
              | "EASY"
              | "RECOVERY"
              | "SHORT_INTERVALS"
              | "HILL_SPRINTS"
              | "LONG_INTERVALS"
              | "SPRINTS"
              | "FARTLEK"
              | "PROGRESSIVE_LONG"
              | "RACE"
              | "TEMPO"
              | "OTHER"
              | null;
            intervalStructureId: number | null;
            analyzedAt: string | null;
            /** @enum {string|null} */
            analysisStatus:
              | "pending"
              | "ongoing_init"
              | "initial"
              | "ongoing_completed"
              | "completed"
              | "error"
              | "skipped_inactive"
              | null;
            draftAnalysisResult?: null;
            analysisVersion: string | null;
            stravaActivityId: number;
            gearId: string | null;
            hasHeartrate: boolean | null;
            title: string;
            description: string | null;
            sportType: string;
            distance: number;
            movingTime: number;
            totalElevationGain: number | null;
            averageHeartRate: number | null;
            startDateLocal: string;
            feeling: number | null;
            notes: string | null;
            createdAt: string | null;
            indoor: boolean;
            intervalsIcuId?: string | null;
            intervalsAnalyzed?: boolean | null;
            intervalsIcuEnrichedAt?: string | null;
            elapsedTime?: number | null;
            maxHeartRate?: number | null;
            averagePower?: number | null;
            weightedAveragePower?: number | null;
            calories?: number | null;
            deviceName?: string | null;
            trainingLoad?: number | null;
            icuTrainingLoad?: number | null;
            icuIntensity?: number | null;
            relativeIntensity?: number | null;
            decoupling?: number | null;
            polarizationIndex?: number | null;
            icuFtp?: number | null;
            icuCtl?: number | null;
            icuAtl?: number | null;
            events?: {
              id: number;
              /** @enum {string} */
              eventType: "INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER";
              bodyLocation: string | null;
              description: string;
              startTime: string;
              lastOccurrence: string;
              /** @enum {string} */
              status: "active" | "resolved";
              resolvedAt: string | null;
            }[];
          };
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Activity not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiActivityGearStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Gear stats */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            stats: {
              gearId: string;
              gearName: string;
              activityCount: number;
              trainingTypeCounts: {
                [key: string]: number;
              };
              distanceKm: number;
            }[];
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiActivityByIdLaps: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Activity laps */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            laps: {
              id: number;
              resource_state: number;
              name: string;
              activity: {
                id: number;
                resource_state: number;
              };
              athlete: {
                id: number;
                resource_state: number;
              };
              elapsed_time: number;
              moving_time: number;
              start_date: string;
              start_date_local: string;
              distance: number;
              start_index: number;
              end_index: number;
              total_elevation_gain: number;
              average_speed: number;
              max_speed: number;
              average_cadence?: number;
              device_watts?: boolean;
              average_watts?: number;
              average_heartrate?: number;
              max_heartrate?: number;
              lap_index: number;
              split: number;
            }[];
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiActivityByIdSplits: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Activity splits */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            splits_metric: {
              distance: number;
              elapsed_time: number;
              elevation_difference: number;
              moving_time: number;
              split: number;
              average_speed: number;
              average_grade_adjusted_speed?: number;
              average_heartrate?: number;
              pace_zone: number;
            }[];
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiActivityByIdHeartrate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Heartrate stream data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiAgentsPending: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pending activities */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            stravaId: number;
            /** @enum {string|null} */
            trainingType:
              | "LONG"
              | "EASY"
              | "RECOVERY"
              | "SHORT_INTERVALS"
              | "HILL_SPRINTS"
              | "LONG_INTERVALS"
              | "SPRINTS"
              | "FARTLEK"
              | "PROGRESSIVE_LONG"
              | "RACE"
              | "TEMPO"
              | "OTHER"
              | null;
            /** @enum {string|null} */
            analysisStatus:
              | "pending"
              | "ongoing_init"
              | "initial"
              | "ongoing_completed"
              | "completed"
              | "error"
              | "skipped_inactive"
              | null;
            draftAnalysisResult?: null;
            title: string;
            notes: string | null;
            distance: number;
            movingTime: number;
            description: string | null;
            indoor: boolean;
            feeling: number | null;
          }[];
        };
      };
    };
  };
  postApiAgentsStartAnalysis: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          activityId: number;
          stravaActivityId: number;
        };
      };
    };
    responses: {
      /** @description Analysis started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  postApiAgentsResumeAnalysis: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          activityId: number;
          notes: string;
          sets?: {
            set_recovery?: number | null;
            steps: {
              /** @enum {string} */
              work_type: "DISTANCE" | "TIME";
              work_value: number;
              /** @enum {string|null} */
              recovery_type?: "DISTANCE" | "TIME" | null;
              recovery_value?: number | null;
              target_pace: number | null;
            }[];
          }[];
          trainingType?: string | null;
          feeling?: number | null;
        };
      };
    };
    responses: {
      /** @description Analysis resumed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  postApiAgentsProposedPace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          structure: {
            set_reps: number;
            steps: {
              reps: number;
              /** @enum {string} */
              work_type: "DISTANCE" | "TIME";
              work_value: number;
              /** @enum {string|null} */
              recovery_type?: "DISTANCE" | "TIME" | null;
              recovery_value?: number | null;
            }[];
            set_recovery?: number | null;
          }[];
          activityId?: number;
        };
      };
    };
    responses: {
      /** @description Proposed paces — one ExpandedIntervalSet per workout set, in order. Empty array if no structure was provided. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            set_recovery?: number | null;
            steps: {
              /** @enum {string} */
              work_type: "DISTANCE" | "TIME";
              work_value: number;
              /** @enum {string|null} */
              recovery_type?: "DISTANCE" | "TIME" | null;
              recovery_value?: number | null;
              target_pace: number | null;
            }[];
          }[];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  postApiAgentsParseIntervals: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          text: string;
          /** @enum {string|null} */
          trainingType?:
            | "LONG"
            | "EASY"
            | "RECOVERY"
            | "SHORT_INTERVALS"
            | "HILL_SPRINTS"
            | "LONG_INTERVALS"
            | "SPRINTS"
            | "FARTLEK"
            | "PROGRESSIVE_LONG"
            | "RACE"
            | "TEMPO"
            | "OTHER"
            | null;
        };
      };
    };
    responses: {
      /** @description Parsed interval sets with proposed paces. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            set_recovery?: number | null;
            steps: {
              /** @enum {string} */
              work_type: "DISTANCE" | "TIME";
              work_value: number;
              /** @enum {string|null} */
              recovery_type?: "DISTANCE" | "TIME" | null;
              recovery_value?: number | null;
              target_pace: number | null;
            }[];
          }[];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiStravaAuthUrl: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authorization URL */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Format: uri */
            url: string;
          };
        };
      };
    };
  };
  postApiStravaAuthExchange: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          code: string;
        };
      };
    };
    responses: {
      /** @description Strava account linked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: string;
          };
        };
      };
      /** @description Missing authorization code */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Not signed in to Clerk, or Strava rejected the code */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiStravaSyncActivities: {
    parameters: {
      query?: {
        page?: string;
        per_page?: string;
        before?: string;
        after?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Strava SummaryActivity[] minus activities we have already synced for this user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": ({
            id: number;
            name: string;
            distance: number;
            moving_time: number;
            elapsed_time: number;
            total_elevation_gain: number;
            type: string;
            sport_type: string;
            start_date: string;
            start_date_local: string;
            timezone: string;
            utc_offset: number;
            trainer: boolean;
            commute: boolean;
            manual: boolean;
            private: boolean;
            average_speed: number;
            max_speed: number;
            has_heartrate: boolean;
            average_heartrate?: number;
            max_heartrate?: number;
            elev_high?: number;
            elev_low?: number;
            gear_id?: string | null;
          } & {
            [key: string]: unknown;
          })[];
        };
      };
      /** @description Missing Strava access token or user */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  postApiStravaSyncActivities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          ids: number[];
        };
      };
    };
    responses: {
      /** @description Per-activity sync result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            /** @enum {string} */
            status: "success" | "failed";
            error?: unknown;
          }[];
        };
      };
      /** @description Missing Strava access token or user */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiStravaWebhookSubscribe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Subscription created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id?: number;
            application_id?: number;
            callback_url?: string;
            created_at?: string;
            updated_at?: string;
          } & {
            [key: string]: unknown;
          };
        };
      };
      /** @description Strava rejected the subscription request (e.g. duplicate) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id?: number;
            application_id?: number;
            callback_url?: string;
            created_at?: string;
            updated_at?: string;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  getApiStravaWebhookSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Subscription list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": ({
            id: number;
            application_id?: number;
            callback_url?: string;
            created_at?: string;
            updated_at?: string;
          } & {
            [key: string]: unknown;
          })[];
        };
      };
    };
  };
  deleteApiStravaWebhookSubscriptionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Subscription deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            message: string;
          };
        };
      };
      /** @description Strava reports the subscription does not exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getApiIntervalStructuresFilter: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of interval structures */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            name: string;
            signature: string | null;
          }[];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiDashboard: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dashboard data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            summary: {
              thisWeekKm: number;
              prevWeekKm: number;
              last7DaysKm: number;
              prev7DaysKm: number;
              weekPercentChange: number;
              sevenDayPercentChange: number;
              weightedWeekPercentChange: number;
              avgKmByThisPointInWeek: number;
              thisWeekElevationGain: number;
              thisWeekMovingTimeSec: number;
              thisWeekAvgHeartRate: number | null;
            };
            graph: {
              date: string;
              runKm: number;
              otherKm: number;
              otherBreakdown: {
                [key: string]: number;
              };
              totalKm: number;
            }[];
            averages: {
              avgSessionsPerWeek: number;
              avgIntervalsPerWeek: number;
              avgFeelingWeek: number | null;
              avgFeelingMonth: number | null;
              avgElevationPerRun: number | null;
              avgDistancePerRunKm: number | null;
            };
            wellness: {
              ctl: number | null;
              atl: number | null;
              tsb: number | null;
              avgHrv: number | null;
              avgSleepQuality: number | null;
              restingHr: number | null;
            } | null;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiDashboardTrainingSummary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Discriminated training-summary result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | {
                /** @constant */
                status: "ok";
                data: {
                  date: string;
                  fitness: {
                    ctl: number | null;
                    atl: number | null;
                    rampRate: number | null;
                    ctlLoad: number | null;
                    atlLoad: number | null;
                  };
                  sleep: {
                    sleepSecs: number | null;
                    sleepScore: number | null;
                  };
                  recovery: {
                    restingHR: number | null;
                    hrv: number | null;
                    readiness: number | null;
                    baevskySI: number | null;
                    spO2: number | null;
                    respiration: number | null;
                  };
                  body: {
                    weight: number | null;
                    vo2max: number | null;
                  };
                };
              }
            | {
                /** @constant */
                status: "not_linked";
                data: null;
              }
            | {
                /** @constant */
                status: "no_recent_data";
                data: null;
              };
        };
      };
    };
  };
  getApiDashboardWellness: {
    parameters: {
      query: {
        oldest: string;
        newest: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Discriminated wellness-series result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | {
                /** @constant */
                status: "ok";
                data: {
                  range: {
                    oldest: string;
                    newest: string;
                  };
                  metricsAvailable: string[];
                  summary: {
                    [key: string]: {
                      latest: number | null;
                      min: number | null;
                      max: number | null;
                      avg: number | null;
                    };
                  };
                  points: {
                    date: string;
                    fitness: {
                      ctl: number | null;
                      atl: number | null;
                      tsb: number | null;
                      rampRate: number | null;
                      ctlLoad: number | null;
                      atlLoad: number | null;
                    };
                    sleep: {
                      sleepSecs: number | null;
                      sleepScore: number | null;
                      sleepQuality: number | null;
                    };
                    recovery: {
                      restingHR: number | null;
                      hrv: number | null;
                      readiness: number | null;
                      baevskySI: number | null;
                      spO2: number | null;
                      respiration: number | null;
                    };
                    subjective: {
                      soreness: number | null;
                      fatigue: number | null;
                      stress: number | null;
                      mood: number | null;
                      motivation: number | null;
                    };
                    health: {
                      injury: number | null;
                      sickness: number | null;
                    };
                    body: {
                      weight: number | null;
                      bodyFat: number | null;
                      vo2max: number | null;
                    };
                    comments: string | null;
                  }[];
                };
              }
            | {
                /** @constant */
                status: "not_linked";
                data: null;
              }
            | {
                /** @constant */
                status: "no_data";
                data: null;
              };
        };
      };
      /** @description Invalid date range */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiDashboardWeekByWeekStart: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        weekStart: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Week detail */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            weekStart: string;
            running: {
              totalKm: number;
              totalElevationGain: number;
              totalMovingTimeSec: number;
              avgHeartRate: number | null;
              avgPaceMinPerKm: number | null;
              numSessions: number;
              indoorSessions: number;
              outdoorSessions: number;
              avgFeeling: number | null;
              percentChangeVsPrevWeek: number | null;
              percentChangeVsSameWeek1MonthAgo: number | null;
              prevWeekKm: number;
              monthAgoWeekKm: number;
              trainingTypeBreakdown: {
                [key: string]: number;
              };
            };
            intervals: {
              count: number;
            };
            otherActivities: {
              combinedKm: number;
              breakdown: {
                sportType: string;
                km: number;
                movingTimeSec: number;
              }[];
            };
            wellness: {
              avgSleepScore: number | null;
              avgFatigue: number | null;
              fitness: number | null;
              form: number | null;
              totalLoad: number | null;
            } | null;
          };
        };
      };
      /** @description Invalid weekStart */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiEvents: {
    parameters: {
      query?: {
        status?: "active" | "resolved";
        eventType?: "INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All events for the user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            events: {
              id: number;
              /** @enum {string} */
              eventType: "INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER";
              bodyLocation: string | null;
              description: string;
              startTime: string;
              lastOccurrence: string;
              /** @enum {string} */
              status: "active" | "resolved";
              resolvedAt: string | null;
              createdAt: string;
              updatedAt: string;
            }[];
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  postApiEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          activityId: number;
          /** @enum {string} */
          eventType: "INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER";
          bodyLocation?: string | null;
          description: string;
          /** Format: date-time */
          startTime?: string;
          /** @enum {string} */
          status?: "active" | "resolved";
        };
      };
    };
    responses: {
      /** @description Created event */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            /** @enum {string} */
            eventType: "INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER";
            bodyLocation: string | null;
            description: string;
            startTime: string;
            lastOccurrence: string;
            /** @enum {string} */
            status: "active" | "resolved";
            resolvedAt: string | null;
            createdAt: string;
            updatedAt: string;
          };
        };
      };
      /** @description Activity not found or unauthorized */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  deleteApiEventsById: {
    parameters: {
      query: {
        activityId: number;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unlink result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            unlinked: boolean;
            deleted: boolean;
          };
        };
      };
      /** @description Event not found or unauthorized */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  patchApiEventsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          eventType?: "INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER";
          bodyLocation?: string | null;
          description?: string;
          /** @enum {string} */
          status?: "active" | "resolved";
        };
      };
    };
    responses: {
      /** @description Updated event */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            /** @enum {string} */
            eventType: "INJURY" | "ILLNESS" | "MEDICAL_VISIT" | "PHYSIO_VISIT" | "OTHER";
            bodyLocation: string | null;
            description: string;
            startTime: string;
            lastOccurrence: string;
            /** @enum {string} */
            status: "active" | "resolved";
            resolvedAt: string | null;
            createdAt: string;
            updatedAt: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Event not found or unauthorized */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            clerkId: string;
            stravaId: string | null;
            /** @enum {string|null} */
            role: "guest" | "premium" | "admin" | null;
            maxHeartRate: number | null;
            processHeartRate: boolean;
            privacyPolicyAcceptedAt: string | null;
            privacyPolicyVersion: string | null;
            currentPrivacyPolicyVersion: string;
            termsOfServiceAcceptedAt: string | null;
            termsOfServiceVersion: string | null;
            currentTermsOfServiceVersion: string;
          };
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  patchApiUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          maxHeartRate?: number | null;
          processHeartRate?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated user profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            clerkId: string;
            stravaId: string | null;
            /** @enum {string|null} */
            role: "guest" | "premium" | "admin" | null;
            maxHeartRate: number | null;
            processHeartRate: boolean;
            privacyPolicyAcceptedAt: string | null;
            privacyPolicyVersion: string | null;
            currentPrivacyPolicyVersion: string;
            termsOfServiceAcceptedAt: string | null;
            termsOfServiceVersion: string | null;
            currentTermsOfServiceVersion: string;
          };
        };
      };
      /** @description Invalid body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  postApiUserAcceptPrivacyPolicy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Acceptance recorded */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            clerkId: string;
            stravaId: string | null;
            /** @enum {string|null} */
            role: "guest" | "premium" | "admin" | null;
            maxHeartRate: number | null;
            processHeartRate: boolean;
            privacyPolicyAcceptedAt: string | null;
            privacyPolicyVersion: string | null;
            currentPrivacyPolicyVersion: string;
            termsOfServiceAcceptedAt: string | null;
            termsOfServiceVersion: string | null;
            currentTermsOfServiceVersion: string;
          };
        };
      };
    };
  };
  postApiUserAcceptTermsOfService: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Acceptance recorded */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            clerkId: string;
            stravaId: string | null;
            /** @enum {string|null} */
            role: "guest" | "premium" | "admin" | null;
            maxHeartRate: number | null;
            processHeartRate: boolean;
            privacyPolicyAcceptedAt: string | null;
            privacyPolicyVersion: string | null;
            currentPrivacyPolicyVersion: string;
            termsOfServiceAcceptedAt: string | null;
            termsOfServiceVersion: string | null;
            currentTermsOfServiceVersion: string;
          };
        };
      };
    };
  };
  deleteApiUserData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All user data deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  postApiIntervalsAuthExchange: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          code: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
