import { sleep } from "bun";
import { asc, eq, inArray } from "drizzle-orm";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { getStravaAccessTokens } from "../src/middlewares/strava_middleware";
import * as schema from "../src/schema";
import { startAnalysis } from "../src/services/analysis_service";

/**
 * Re-analyze every pending-review (`initial`) activity with the CURRENT code, to
 * refresh drifted drafts (this session's segmentation + classification fixes) and
 * let us review each. Uses the force path (bypasses SKIP_START_STATUSES, resets the
 * thread). Paced to stay under Strava/icu rate limits. Writes a review report.
 *
 * MUTATES the dev DB. Makes gpt-4o-mini calls. Run: bun run scripts/rerun_pending.ts
 */

const STATUSES = (process.env.STATUSES ?? "initial").split(",");
const DELAY_MS = Number(process.env.DELAY_MS ?? 2500);
const OUT =
  process.env.OUT ??
  "/Users/carlvaldemarebbesen/Development/intervals/knowledge/knowledge/sources/activity-dumps/RERUN_PENDING.md";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle({ client: pool, schema });

function countReps(structure: any): number {
  if (!Array.isArray(structure)) return 0;
  let n = 0;
  for (const set of structure) {
    const stepReps = (set.steps ?? []).reduce((a: number, st: any) => a + (st.reps ?? 1), 0);
    n += (set.set_reps ?? 1) * stepReps;
  }
  return n;
}

async function main() {
  const acts = (
    await db
      .select()
      .from(schema.activities)
      .where(inArray(schema.activities.analysisStatus, STATUSES))
      .orderBy(asc(schema.activities.startDateLocal))
  ) as any[];
  const limited = process.env.LIMIT ? acts.slice(0, Number(process.env.LIMIT)) : acts.slice();
  console.log(
    `[rerun] ${limited.length}/${acts.length} activities in [${STATUSES.join(",")}], delay=${DELAY_MS}ms`,
  );
  acts.length = 0;
  acts.push(...limited);

  const tokenCache = new Map<string, string>();
  const rows: any[] = [];

  for (let i = 0; i < acts.length; i++) {
    const act = acts[i];
    const userRow = (
      await db
        .select({ clerkId: schema.users.clerkId })
        .from(schema.users)
        .where(eq(schema.users.id, act.userId))
    )[0] as any;
    const clerkId = userRow?.clerkId as string | undefined;
    let token = "";
    if (clerkId) {
      if (!tokenCache.has(clerkId)) {
        try {
          tokenCache.set(clerkId, (await getStravaAccessTokens(clerkId)).access_token);
        } catch {
          tokenCache.set(clerkId, "");
        }
      }
      token = tokenCache.get(clerkId) ?? "";
    }

    const t0 = Date.now();
    try {
      await startAnalysis(db, token, act.id, act.stravaActivityId ?? null, act.userId, true);
    } catch (e) {
      console.log(`[rerun] ${act.id} threw: ${e instanceof Error ? e.message : e}`);
    }

    const fresh = (
      await db
        .select({ draft: schema.activities.draftAnalysisResult, status: schema.activities.analysisStatus })
        .from(schema.activities)
        .where(eq(schema.activities.id, act.id))
    )[0] as any;
    const draft = fresh?.draft ?? {};
    const structReps = countReps(draft?.structure);
    const propSegs = Array.isArray(draft?.proposedSegments) ? draft.proposedSegments.length : null;
    const propIntervals = Array.isArray(draft?.proposedSegments)
      ? draft.proposedSegments.filter((s: any) => s.type === "INTERVALS").length
      : null;
    const rec = {
      id: act.id,
      title: act.title,
      indoor: act.indoor,
      type: draft?.training_type ?? null,
      conf: draft?.confidence_score ?? null,
      structReps,
      propIntervals,
      propSegs,
      status: fresh?.status,
      ms: Date.now() - t0,
    };
    rows.push(rec);
    console.log(
      `[rerun] ${i + 1}/${acts.length} id=${act.id} "${String(act.title).slice(0, 26)}" type=${rec.type} structReps=${structReps} intervals=${propIntervals}/${propSegs} status=${rec.status} ${rec.ms}ms`,
    );
    if (i < acts.length - 1) await sleep(DELAY_MS);
  }

  const lines = [
    "# Pending re-analysis review (current code)",
    "",
    `${rows.length} activities re-analyzed. Generated by scripts/rerun_pending.ts.`,
    "",
    "| id | title | indoor | type | conf | structReps | intervals/segs | status | flag |",
    "|---|---|---|---|---|---|---|---|---|",
    ...rows.map((r) => {
      // flag = INTERVALS count disagrees with the extracted structure rep count
      const flag =
        r.structReps > 0 && r.propIntervals != null && r.propIntervals !== r.structReps
          ? `⚠️ ${r.propIntervals}≠${r.structReps}`
          : "";
      return `| ${r.id} | ${String(r.title).replace(/\|/g, "/").slice(0, 30)} | ${r.indoor ? "Y" : ""} | ${r.type} | ${r.conf} | ${r.structReps} | ${r.propIntervals}/${r.propSegs} | ${r.status} | ${flag} |`;
    }),
  ];
  await Bun.write(OUT, lines.join("\n"));
  console.log(`[rerun] done. report=${OUT}`);
  await pool.end();
}

main().catch(async (e) => {
  console.error("[rerun] fatal:", e);
  await pool.end().catch(() => {});
  process.exit(1);
});
