import { pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";
import { trainingTypeEnum } from "./enums";
import { relations } from "drizzle-orm";
import { activities } from "./activities";

/**
 * INTERVAL STRUCTURES (New Requirement)
 * Stores unique definitions of workouts (e.g., "10x400m" or "Pyramid 1-2-3").
 * Created on demand when a new structure is identified.
 */
export const intervalStructures = pgTable('interval_structures', {
  id: serial('id').primaryKey(),
  
  // A human-readable name generated by your backend logic
  // e.g. "Pyramid: 1k-2k-1k" or "10x400m Repeats"
  name: text('name').notNull(),
  
  // A technical signature to detect duplicates easily
  // e.g. "WORK:1000|WORK:2000|WORK:1000" or a JSON hash
  signature: text('signature').unique(), 
  trainingType: trainingTypeEnum('training_type').notNull(), // Default category for this workout
  createdAt: timestamp('created_at').defaultNow(),
});


export const intervalStructuresRelations = relations(intervalStructures, ({ many }) => ({
  activities: many(activities),
}));